Automatic install of GitHub CLI, Git and Git LFS (see ticket #7)
ProjectBorealis/PBSync pull request #34
Opened 2024-11-30 10:58 UTC by User21T

I added **_requests_** and **_urllib3_** in the first place to handle downloading files from Internet via Python script. Then I rewrited code in pbsync/__main__.py to allow PBSync for automatic install of GitHub CLI (if not available), Microsoft's Git and Git LFS.
First, the program checks whether GitHub isn't already installed. If yes, then it proceeds forward. Otherwise, it starts downloading installation file for GH Cli. When downloading fails once, the program will repeat the process 5 times at most until it stops. If download and installation process is successful, then it downloads and installs Git and Git LFS via GitHub CLI.
Workflow is improved, because we don't have to download separately by the browser. We can repeat the version check/install process.

2025-05-06 14:18 UTC, mastercoms commented on Pipfile
> +requests = "*"
I'd like to avoid including new libraries for this, we can probably use the ones within the standard library

2025-05-06 14:25 UTC, mastercoms requested changes
Looks good for the most part, the upgraded download logic looks nice!

2025-05-06 14:25 UTC, mastercoms commented on pbsync/__main__.py
> +def install_gh_cli():
GitHub CLI is expected to be in `.github/git/gh.exe`,  please see `pbgh.py`. Though, I suppose we need to do some work to fix support for GitHub CLI while using repos on GitLab, since it uses GitLab CLI automatically in that case. So maybe forcing GitHub CLI is good there.

2025-05-06 14:25 UTC, mastercoms commented on Pipfile
> +requests = "*"
We use `urllib.request` in other places, so if we are including the requests package, we should probably avoid importing `urllib.request` throughout.

2025-05-06 14:25 UTC, mastercoms commented on pbsync/__main__.py
> +retry_strategy = Retry(
Maybe make a new `pbhttp` module in pbpy?

2025-12-19 08:43 UTC, user21t commented
@mastercoms I see you have fixed the problem by yourself, haven't you? I mean implementing your own download logic in updated repository.

2025-12-19 10:48 UTC, mastercoms commented
It isn't implemented yet, I have just moved logic around. I was planning to integrate your changes into the refactored logic soon.

2026-03-01 23:06 UTC, user21t commented
Hello. Are my commits still needed?

2026-03-07 02:33 UTC, mastercoms commented
Hi, I plan to integrate your changes very soon. Just need to get around to working on this project again. Right now my time has been spent developing things in the engine.

2026-04-13 19:03 UTC, user21t commented
I know it's kinda late, but I must admit I used Claude's LLM to create this pull request, so you can close it without explanation and add your own handmade changes.

2026-04-13 21:26 UTC, closed without merging